### ISSUE TITLE
ReleaseNewBuild does not delete local tags removed from Github prior to doing a build

### ISSUE THREAD

**Issue by norberturkiewicz** [the-carlisle-group/AcreTools#109]
This causes Dado to push all local outdated tags back to GitHub.

In git bash

Delete all tags
`git tag -d $(git tag)`

Get tags from GitHub
`git fetch --tags`

**Comment by PaulMansour** [comment]
Ok, agree to do.

**Comment by PaulMansour** [comment]
The issue here is that the Dado PushMaster command pushes all tags with --tags, a bad practice. The --tags options should be removed from PushMaster.  In ReleaseNewVersion, we should do a push with --follow-tags, which will only push the tags of the outstanding commits being pushed, which is by definition just the single commit for the new release.

**Comment by PaulMansour** [comment]
Fixed
